name: Nest.js CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Nest.js CI']
    types: [completed]
    branches: [main]

jobs:
  deploy:
    # workflow 완료 후 결과가 성공 일 때
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # 작업을 실행 할 VM의 OS 지정
    runs-on: ubuntu-24.04

    steps:
      - name: Upload script to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PEM_KEY }}
          port: ${{ secrets.AWS_EC2_PORT }}
          source: ./.github/scripts/deploy.sh
          target: /home/ubuntu/deploy.sh

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PEM_KEY }}
          port: ${{ secrets.AWS_EC2_PORT }}
          envs: ENVIRONMENT
          script: |
            chmod +x /home/ubuntu/deploy.sh
            /home/ubuntu/deploy.sh

            # export NVM_DIR="$HOME/.nvm"
            # [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            # [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

            # cd /home/ubuntu/dkuac_be

            # git switch main

            # git pull

            # echo "$ENVIRONMENT" > .env

            # npm ci

            # npm run build

            # pm2 delete dkuac-server

            # pm2 --name dkuac-server start dist/src/main.js

            # pm2 save
